"""initial schema

Creates the thirteen tables of ``docs/02-architecture/data-model.md``, the pgvector
extension they depend on, and the database-level guarantee that ``events`` is
append-only (ADR-008). Autogenerated from ``app/models`` and then extended by hand
with the extension, the cycle-breaking foreign key, and the immutability block.

Revision ID: 0001
Revises:
Create Date: 2026-07-29

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- ADR-008: events immutability --------------------------------------------
#
# Immutability of the audit log is a *database* property, not an application
# convention: "an audit log that application code can UPDATE is not an audit log".
# Two mechanisms, because either alone leaves a hole:
#
# 1. GRANTS — the mechanism ADR-008 names. The application role `forge_app` holds
#    INSERT and SELECT on `events`; UPDATE, DELETE and TRUNCATE are revoked. An
#    application bug cannot rewrite history because the connection has no such right.
#
# 2. A TRIGGER — because PostgreSQL exempts a table's *owner* from its own grants
#    (and superusers from all of them). The demo connects as the owner for
#    simplicity, so grants alone would be documentation rather than enforcement.
#    The trigger raises on UPDATE/DELETE/TRUNCATE for every role, owner included,
#    and it is what the append-only test in tests/test_events_append_only.py proves.
#
# Corrections are made by writing compensating events, never by editing one.
# Hardening step for a real deployment: point DATABASE_URL at `forge_app`
# (ALTER ROLE forge_app LOGIN PASSWORD ... — credentials belong to the deployment,
# never to a migration) so layer 1 also bites at runtime.

APP_ROLE = "forge_app"

CREATE_APP_ROLE = f"""
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
        -- NOLOGIN: a migration must never create a credential. The deployment
        -- grants login and a password when it wants to use this role.
        CREATE ROLE {APP_ROLE} NOLOGIN;
    END IF;
END
$$;
"""

GRANT_APP_ROLE = f"""
GRANT USAGE ON SCHEMA public TO {APP_ROLE};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {APP_ROLE};

-- The audit log is the exception: insert and read, nothing else. Ever.
REVOKE ALL ON TABLE events FROM {APP_ROLE};
REVOKE ALL ON TABLE events FROM PUBLIC;
GRANT INSERT, SELECT ON TABLE events TO {APP_ROLE};
"""

CREATE_IMMUTABILITY_TRIGGER = """
CREATE OR REPLACE FUNCTION forge_events_are_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'events is append-only (ADR-008): % is not permitted', TG_OP
        USING ERRCODE = 'restrict_violation',
              HINT = 'Record a compensating event instead of editing history.';
END
$$;

CREATE TRIGGER events_reject_update
    BEFORE UPDATE ON events
    FOR EACH ROW EXECUTE FUNCTION forge_events_are_append_only();

CREATE TRIGGER events_reject_delete
    BEFORE DELETE ON events
    FOR EACH ROW EXECUTE FUNCTION forge_events_are_append_only();

CREATE TRIGGER events_reject_truncate
    BEFORE TRUNCATE ON events
    FOR EACH STATEMENT EXECUTE FUNCTION forge_events_are_append_only();
"""

DROP_IMMUTABILITY_TRIGGER = """
DROP TRIGGER IF EXISTS events_reject_truncate ON events;
DROP TRIGGER IF EXISTS events_reject_delete ON events;
DROP TRIGGER IF EXISTS events_reject_update ON events;
DROP FUNCTION IF EXISTS forge_events_are_append_only();
"""

REVOKE_APP_ROLE = f"""
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM {APP_ROLE};
REVOKE ALL ON SCHEMA public FROM {APP_ROLE};
"""


def upgrade() -> None:
    # pgvector must exist before knowledge_chunks.embedding can be created (ADR-004).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "tenants",
        sa.Column(
            "tenant_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False, comment="chatbot | workflow | autonomous"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_agents_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_agents_tenant_id_slug")),
    )
    op.create_index(op.f("ix_agents_tenant_id"), "agents", ["tenant_id"], unique=False)
    op.create_table(
        "eval_suites",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False, comment="semver"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_eval_suites_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_suites")),
        sa.UniqueConstraint(
            "tenant_id", "slug", "version", name=op.f("uq_eval_suites_tenant_id_slug_version")
        ),
    )
    op.create_index(op.f("ix_eval_suites_tenant_id"), "eval_suites", ["tenant_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("event_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Text(),
            nullable=False,
            comment="run.started, decision.made, approval.granted, version.published, ...",
        ),
        sa.Column("actor", sa.Text(), nullable=False, comment="system or user id"),
        sa.Column("run_id", sa.UUID(), nullable=True, comment="soft ref, nullable"),
        sa.Column("agent_version_id", sa.UUID(), nullable=True, comment="soft ref, nullable"),
        sa.Column("approval_id", sa.UUID(), nullable=True, comment="soft ref, nullable"),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="typed by event type",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_events")),
    )
    op.create_index("ix_events_run_id_event_id", "events", ["run_id", "event_id"], unique=False)
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_collections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "authority_level",
            sa.Text(),
            nullable=False,
            comment="sme_validated | policy_2023 | policy_2019",
        ),
        sa.Column("owner", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_knowledge_collections_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_collections")),
        sa.UniqueConstraint(
            "tenant_id", "slug", name=op.f("uq_knowledge_collections_tenant_id_slug")
        ),
    )
    op.create_index(
        op.f("ix_knowledge_collections_tenant_id"),
        "knowledge_collections",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False, comment="semver"),
        sa.Column(
            "dna",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="validated vs dna-schema.json at write",
        ),
        sa.Column("status", sa.Text(), nullable=False, comment="draft | published | suspended"),
        sa.Column(
            "published_eval_run_id", sa.UUID(), nullable=True, comment="gate evidence, nullable"
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(dna) = 'object'", name=op.f("ck_agent_versions_dna_is_object")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_agent_versions_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_agent_versions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_versions")),
        sa.UniqueConstraint("agent_id", "version", name=op.f("uq_agent_versions_agent_id_version")),
        # published_eval_run_id -> eval_runs.id is added at the end of this migration:
        # the two tables reference each other, so one side must be an ALTER TABLE.
    )
    op.create_index(
        op.f("ix_agent_versions_agent_id"), "agent_versions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_versions_tenant_id"), "agent_versions", ["tenant_id"], unique=False
    )
    op.create_table(
        "eval_cases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("suite_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False, comment="E-xx"),
        sa.Column("scenario", sa.Text(), nullable=False),
        sa.Column("expected_action", sa.Text(), nullable=False),
        sa.Column(
            "expected_citations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="R-xxx list",
        ),
        sa.Column(
            "must_not_call",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="e.g. approve_invoice",
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["eval_suites.id"], name=op.f("fk_eval_cases_suite_id_eval_suites")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_eval_cases_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_cases")),
        sa.UniqueConstraint("suite_id", "code", name=op.f("uq_eval_cases_suite_id_code")),
    )
    op.create_index(op.f("ix_eval_cases_suite_id"), "eval_cases", ["suite_id"], unique=False)
    op.create_index(op.f("ix_eval_cases_tenant_id"), "eval_cases", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=True, comment="document or rule id"),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("rule_id", sa.Text(), nullable=True, comment="R-xxx, nullable"),
        sa.Column("authority_level", sa.Text(), nullable=False, comment="denormalized for ranking"),
        sa.Column("content", sa.Text(), nullable=False),
        # Dimensionless vector: the embedding model (and therefore the width and the
        # ANN index) is chosen with the knowledge layer in Phase 4.3.
        sa.Column("embedding", Vector(), nullable=True, comment="pgvector, semantic"),
        sa.Column(
            "lexical_tsv", postgresql.TSVECTOR(), nullable=True, comment="full-text, lexical"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["knowledge_collections.id"],
            name=op.f("fk_knowledge_chunks_collection_id_knowledge_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_knowledge_chunks_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_collection_id"),
        "knowledge_chunks",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_chunks_lexical_tsv",
        "knowledge_chunks",
        ["lexical_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_knowledge_chunks_rule_id"), "knowledge_chunks", ["rule_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_tenant_id"), "knowledge_chunks", ["tenant_id"], unique=False
    )
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("suite_id", sa.UUID(), nullable=False),
        sa.Column("agent_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, comment="running | completed"),
        sa.Column("passed", sa.Boolean(), nullable=True, comment="publish-gate result"),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("passed_count", sa.Integer(), nullable=True),
        sa.Column(
            "case_results",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="per-case pass/fail detail",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_eval_runs_agent_version_id_agent_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"], ["eval_suites.id"], name=op.f("fk_eval_runs_suite_id_eval_suites")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_eval_runs_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    op.create_index(
        op.f("ix_eval_runs_agent_version_id"), "eval_runs", ["agent_version_id"], unique=False
    )
    op.create_index(op.f("ix_eval_runs_suite_id"), "eval_runs", ["suite_id"], unique=False)
    op.create_index(op.f("ix_eval_runs_tenant_id"), "eval_runs", ["tenant_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("agent_version_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Text(),
            nullable=False,
            comment="running | awaiting_approval | completed | escalated | canceled | error",
        ),
        sa.Column("trigger", sa.Text(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("total_cost_usd", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_runs_agent_version_id_agent_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_runs_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_agent_version_id"), "runs", ["agent_version_id"], unique=False)
    op.create_index(op.f("ix_runs_tenant_id"), "runs", ["tenant_id"], unique=False)
    op.create_table(
        "run_steps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False, comment="reason | tool | decision"),
        sa.Column(
            "model_call",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="model, tokens, cost",
        ),
        sa.Column(
            "decision",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="action plus rule citations (R-xxx); a decision without citations is a bug",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_run_steps_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_run_steps_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
        sa.UniqueConstraint("run_id", "step_no", name=op.f("uq_run_steps_run_id_step_no")),
    )
    op.create_index(op.f("ix_run_steps_run_id"), "run_steps", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_steps_tenant_id"), "run_steps", ["tenant_id"], unique=False)
    op.create_table(
        "tool_invocations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("run_step_id", sa.UUID(), nullable=False),
        sa.Column("tool_ref", sa.Text(), nullable=False, comment="slug at semver"),
        sa.Column(
            "autonomy",
            sa.Text(),
            nullable=False,
            comment="autonomous | requires_approval | forbidden",
        ),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status", sa.Text(), nullable=False, comment="validated | executed | blocked | denied"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_tool_invocations_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["run_step_id"],
            ["run_steps.id"],
            name=op.f("fk_tool_invocations_run_step_id_run_steps"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_tool_invocations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_invocations")),
    )
    op.create_index(
        op.f("ix_tool_invocations_run_id"), "tool_invocations", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_run_step_id"), "tool_invocations", ["run_step_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_tenant_id"), "tool_invocations", ["tenant_id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("tool_invocation_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.Text(), nullable=False, comment="pending | granted | rejected | expired"
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="server-side, fail-closed",
        ),
        sa.Column(
            "decision", sa.Text(), nullable=True, comment="approve | reject, null until decided"
        ),
        sa.Column("decided_by", sa.Text(), nullable=True, comment="actor"),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_approvals_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_approvals_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["tool_invocation_id"],
            ["tool_invocations.id"],
            name=op.f("fk_approvals_tool_invocation_id_tool_invocations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("tool_invocation_id", name=op.f("uq_approvals_tool_invocation_id")),
    )
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_index(op.f("ix_approvals_tenant_id"), "approvals", ["tenant_id"], unique=False)

    # Closes the agent_versions <-> eval_runs cycle: a published version points at the
    # eval run that satisfied its gate, and that eval run points back at the version.
    op.create_foreign_key(
        op.f("fk_agent_versions_published_eval_run_id_eval_runs"),
        "agent_versions",
        "eval_runs",
        ["published_eval_run_id"],
        ["id"],
    )

    # ADR-008 — see the module docstring above for why both layers exist.
    op.execute(CREATE_APP_ROLE)
    op.execute(GRANT_APP_ROLE)
    op.execute(CREATE_IMMUTABILITY_TRIGGER)


def downgrade() -> None:
    op.execute(DROP_IMMUTABILITY_TRIGGER)
    op.execute(REVOKE_APP_ROLE)
    # The role itself is deliberately left in place: roles are cluster-scoped, so
    # dropping it here could break another database that still uses it.

    op.drop_constraint(
        op.f("fk_agent_versions_published_eval_run_id_eval_runs"),
        "agent_versions",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_approvals_tenant_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_tool_invocations_tenant_id"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_run_step_id"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_run_id"), table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index(op.f("ix_run_steps_tenant_id"), table_name="run_steps")
    op.drop_index(op.f("ix_run_steps_run_id"), table_name="run_steps")
    op.drop_table("run_steps")
    op.drop_index(op.f("ix_runs_tenant_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_agent_version_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_eval_runs_tenant_id"), table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_suite_id"), table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_agent_version_id"), table_name="eval_runs")
    op.drop_table("eval_runs")
    op.drop_index(op.f("ix_knowledge_chunks_tenant_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_rule_id"), table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_lexical_tsv", table_name="knowledge_chunks", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_knowledge_chunks_collection_id"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_eval_cases_tenant_id"), table_name="eval_cases")
    op.drop_index(op.f("ix_eval_cases_suite_id"), table_name="eval_cases")
    op.drop_table("eval_cases")
    op.drop_index(op.f("ix_agent_versions_tenant_id"), table_name="agent_versions")
    op.drop_index(op.f("ix_agent_versions_agent_id"), table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_index(op.f("ix_knowledge_collections_tenant_id"), table_name="knowledge_collections")
    op.drop_table("knowledge_collections")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_index("ix_events_run_id_event_id", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_eval_suites_tenant_id"), table_name="eval_suites")
    op.drop_table("eval_suites")
    op.drop_index(op.f("ix_agents_tenant_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("tenants")
    # The `vector` extension is intentionally left installed: other databases or
    # migrations may rely on it, and dropping an extension is not this migration's call.
